"""Derive gta4_pal_config.toml from the US gta4_config.toml.

Every address in the US config is remapped with remap_sources.Resolver (US generated tree vs the PAL
reference tree generated_pal_raw/), then the PAL-only branch targets that PAL codegen validation needs
(taken from gta4_pal_raw_config.toml) are merged into [functions]. Fails on any duplicate key.

usage: build_pal_config.py <gta4-recomp dir>
"""
import collections, os, re, sys

sys.path.insert(0, os.path.dirname(__file__))
import match_functions as mf
import remap_sources as rs

root = sys.argv[1]
res = rs.Resolver(mf.build_map(f'{root}/generated', f'{root}/generated_pal_raw', log=lambda *_: None))
us_cfg = open(f'{root}/gta4_config.toml').read()
stats, unresolved = collections.Counter(), []
out = rs.rewrite_text(us_cfg, res, stats, unresolved, 'gta4_config.toml')
out = out.replace('# Xbox 360 Static Recompilation - v8 (0.0.8.5)',
                  '# PAL port: base 7 + TU5 (0.0.5.7). GENERATED by tools/xex/build_pal_config.py from the US\n'
                  '# v8 config; do not edit by hand - change the US config or tools/xex/manual_map.json and rerun.')
real = [u for u in unresolved if not u[3].lstrip().startswith('#') and not re.search(r'#.*' + u[2], u[3])]
if real:
    sys.exit('unresolved addresses in non-comment config text:\n' + '\n'.join(map(str, real)))

have = set(re.findall(r'^"(0x[0-9A-Fa-f]{8})"', out, re.M))
raw = open(f'{root}/gta4_pal_raw_config.toml').read()
extra = [l for l in raw[raw.index('[functions]'):].splitlines()
         if l.startswith('"0x') and l.split('"')[1] not in have]
i = out.index('[functions]'); j = out.index('\n', i) + 1
out = out[:j] + '# PAL-only cross-function branch targets required by PAL codegen validation.\n' + \
    ''.join(l + '\n' for l in extra) + out[j:]

keys = re.findall(r'^"(0x[0-9A-Fa-f]{8})"', out, re.M)
dups = [k for k, n in collections.Counter(keys).items() if n > 1]
if dups:
    sys.exit(f'duplicate [functions] keys after remap: {dups}')
open(f'{root}/gta4_pal_config.toml', 'w').write(out)
print(f'wrote gta4_pal_config.toml: {dict(stats)}; {len(extra)} PAL-only entries; '
      f'{len(unresolved)} unresolved (comments only)')
